host: javaroadmap.ru

logging:
  file:
    name: '/var/log/jrm-server.log'
  level:
    root: WARN

spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://92.53.65.165:5432/javaroadmap
    username: postgres
    password: changeme
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

javaroadmap:
  api:
    base-v1-url: http://${host}:8081/api/v1/


